---
- name: Install php7.0-fpm and deps
  apt: name={{ item }} state=present
  with_items:
    - php7.0
    - php7.0-fpm
    - php7.0-mysql

#- name: Disable default pool
#  command: mv /etc/php/7.0/fpm/pool.d/www.conf /etc/php/7.0/fpm/www.disabled creates=/etc/php-fpm.d/www.disabled
#  notify: restart php7.0-fpm

- name: Copy php7.0-fpm configuration
  template: src=wordpress.conf dest=/etc/php/7.0/fpm/
  notify: restart php7.0-fpm
